name: api_training
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0-323.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sizer: ^2.0.15
  auto_route: ^8.3.0
  cached_network_image: ^3.3.1
  flutter_bloc: ^8.1.6
  talker_flutter: ^4.3.4
  talker_bloc_logger: ^4.3.4
  get_it: ^7.7.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  google_fonts: ^6.2.1
  awesome_snackbar_content: ^0.1.3
  loading_animation_widget: ^1.2.1
  hive_flutter: ^1.1.0
  modal_bottom_sheet: ^3.0.0
  dio: ^5.5.0+1
  flutter_native_splash: ^2.4.1
  rive: ^0.13.9
  google_nav_bar: ^5.0.6
  flutter_map: ^7.0.2

flutter_native_splash:
    android: true
    ios: true
    web: true
    background_image: 'assets/image.png'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  auto_route_generator: ^8.0.0
  freezed: ^2.5.3
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1


flutter:

  uses-material-design: true

  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
